// export const INITIAL_STATE = 'Payment/INITIAL_STATE';

export const GET_INCIDENT_REQ = 'Home/GET_INCIDENT_REQ/REQUEST/SHOW_LOADER';
export const GET_INCIDENT_RES = 'Home/GET_INCIDENT_RES/RESPONSE/HIDE_LOADER';
// export const PAY_DEBIT_CREDIT_CARD_REQ = 'Payment/PAY_DEBIT_CREDIT_CARD_REQ/REQUEST/SHOW_LOADER';
// export const PAY_DEBIT_CREDIT_CARD_RES = 'Payment/PAY_DEBIT_CREDIT_CARD_RES/RESPONSE/HIDE_LOADER';
// export const GET_OTP_RESPONSE_REQ = 'Payment/GET_OTP_RESPONSE_REQ/REQUEST/SHOW_LOADER';
// export const GET_OTP_RESPONSE_RES = 'Payment/GET_OTP_RESPONSE_RES/RESPONSE/HIDE_LOADER';
